# [package]
# org= "ballerinax"
# name= "slackn"
# version= "0.0.1-SNAPSHOT"

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-0.9.9-SNAPSHOT.jar"
groupId = "io.ballerinax.slack"
artifactId = "java-wrapper"
version = "0.9.9-SNAPSHOT"
