[package]
org = "ballerinax"
name = "asyncapi.native.handler"
version = "0.5.1-SNAPSHOT"
distribution = "2201.11.0"
readme = "Package.md"

[[platform.java21.dependency]]
path = "./java-wrapper/build/libs/java-wrapper-0.10.1-SNAPSHOT.jar"
groupId = "io.ballerinax.asyncapi"
artifactId = "java-wrapper"
version = "0.10.1"

[build-options]
observabilityIncluded = true
