[package]
org = "ballerinax"
name = "asyncapi.native.handler"
version = "0.4.0"
export= ["asyncapi.native.handler"]

[[platform.java17.dependency]]
path = "./java-wrapper/build/libs/java-wrapper-0.9.0-beta.3-SNAPSHOT.jar"
groupId = "io.ballerinax.asyncapi"
artifactId = "java-wrapper"
version = "0.9.9-SNAPSHOT"

[build-options]
observabilityIncluded = true
